### PR TITLE
Fix max_query_time for ccp_connection_stats

### PR DESCRIPTION
**Pull request by cbrianpace**
# Description  

*Please fill this template out fully; failure to do so can result in rejection of your PR.*

Please describe the changes made by your PR. This description should be at a high-level but detailed enough that a reviewer understands the scope of the fix or enhancement and can easily judge the PRs validity at addressing the stated issue/feature. Please fully describe any new or changed feature and whether said change is user-facing or not:

The max_query_time was not filtering out sessions that were in 'idle in transaction'.  Adjusted query to exclude idle and idle in transaction sessions from max_query_time.

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [X] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [ ] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [X] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [ ] Other:  
- [X] PostgreSQL, Specify version(s):  13,14,15
- [ ] docs tested with hugo version(s):  

### Code testing

Have you tested your changes against:
- [X] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [ ] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [X] Ensure that exporter runs with no scrape errors
- [ ] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [X] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [X] Not applicable

If your code touches Grafana, have you:
- [ ] Ensured Grafana runs without issue
- [ ] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

### CODE REVIEW

**Review by hunleyd — CHANGES_REQUESTED** [review]
needs a changelog fragment, otherwise LGTM

**Comment by keithf4** [comment]
> needs a changelog fragment, otherwise LGTM

I can create these once approved

**Review by keithf4 — APPROVED** [review]

**Review by hunleyd — APPROVED** [review]

**Review by jchancojr — CHANGES_REQUESTED** [review]
same as other pr (changelog?)

**Review by jchancojr — APPROVED** [review]
retract fragment comment

**Pull request merged**
