### PR TITLE
Ensure consistent default settings for grafana dashboards

### PR DESCRIPTION
**Pull request by keithf4**
Reviewed all dashboards for consistent settings. Only 3 dashboards were not consistent. Below are the settings I checked for and which ones I had to fix.

Set all but Overviews to 15 min refresh, and ensure none are editable. Overview and Prometheus set to 5m refresh

Top Overview - N/A
PostgreSQL Overview - 5 min window
OS Overview - 5 min window
ETCD Details - 2 day window
Prometheus Alerts - 2 day window
OS Details - 2 day window
OS Details Windows - 2 day window (was 3hrs). Changed refresh from 10s to 15m
Filesystem Details - 2 day window
PostgreSQL Details - 2 day window (was 30 minutes)
TableSize details - 2 day window
CRUD Details - 2 day window
Bloat Details - 2 day window
PGBouncer - 2 day window (was 7 days), was editable 
PGBackrest - 2 week window (was 3hrs). had no refresh. now set to 15 mins

### CODE REVIEW

**Comment by sharmay** [comment]
https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/PG_Overview.json#L141
https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/OS_Overview.json#L136

overview provide up/down or Replica/Primary status, refresh rate of 15M of them seems too long, these overview shall be able to quickly show the changes like in 60s

**Comment by keithf4** [comment]
> 
> 
> https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/PG_Overview.json#L141
> https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/OS_Overview.json#L136
> 
> overview provide up/down or Replica/Primary status, refresh rate of 15M of them seems too long, these overview shall be able to quickly show the changes like in 60s

60s is way too frequent a default IMO. We had them at 15s or 30s on our internal dashboards by accident and just 3 or 4 people keeping those dashboards open and refreshing was pegging the CPU and crashing the web server. I went with 15mins across the board in general and would say no lower than maybe 5 mins for the Overview, if we even really feel the need to change this. 

If people really need to change the refresh rate to keep an eye on something, they can do so whenever they wish. We should keep the defaults at something that will not kill the web server by accident when 5-10 people are all looking at it at the same time.

**Comment by sharmay** [comment]
> > https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/PG_Overview.json#L141
> > https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/OS_Overview.json#L136
> > overview provide up/down or Replica/Primary status, refresh rate of 15M of them seems too long, these overview shall be able to quickly show the changes like in 60s
> 
> 60s is way too frequent a default IMO. We had them at 15s or 30s on our internal dashboards by accident and just 3 or 4 people keeping those dashboards open and refreshing was pegging the CPU and crashing the web server. I went with 15mins across the board in general and would say no lower than maybe 5 mins for the Overview, if we even really feel the need to change this.
> 
> If people really need to change the refresh rate to keep an eye on something, they can do so whenever they wish. We should keep the defaults at something that will not kill the web server by accident when 5-10 people are all looking at it at the same time.



> > https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/PG_Overview.json#L141
> > https://github.com/keithf4/pgmonitor/blob/grafana_defaults/grafana/OS_Overview.json#L136
> > overview provide up/down or Replica/Primary status, refresh rate of 15M of them seems too long, these overview shall be able to quickly show the changes like in 60s
> 
> 60s is way too frequent a default IMO. We had them at 15s or 30s on our internal dashboards by accident and just 3 or 4 people keeping those dashboards open and refreshing was pegging the CPU and crashing the web server. I went with 15mins across the board in general and would say no lower than maybe 5 mins for the Overview, if we even really feel the need to change this.
> 

15s is 4x of 60s and 30s is 2x of it, compare it with 15m I guess it is too slow of update.

> If people really need to change the refresh rate to keep an eye on something, they can do so whenever they wish. We should keep the defaults at something that will not kill the web server by accident when 5-10 people are all looking at it at the same time.

Argument can be other way round too.

**Comment by keithf4** [comment]
> > 60s is way too frequent a default IMO. We had them at 15s or 30s on our internal dashboards by accident and just 3 or 4 people keeping those dashboards open and refreshing was pegging the CPU and crashing the web server. I went with 15mins across the board in general and would say no lower than maybe 5 mins for the Overview, if we even really feel the need to change this.
> 
> 15s is 4x of 60s and 30s is 2x of it, compare it with 15m I guess it is too slow of update.
> 

Right, now also multiply that by 5-10, or more likely even more, people looking at the dashboard at the same time. You do remember when we killed our webserver with just 3-4 people right?

Other thing to keep in mind is, because these are single value panels, the values shown in the Overview are averages of the time period that the window is limited to. So actually, going below 5 minutes is kind of pointless because, despite us asking for the "current" value in Grafana, it still does some sort of an average of the 5 minute window we set on the overview dashboards. It still takes several minutes for these panels to update when we failover or the system goes down. 

> > If people really need to change the refresh rate to keep an eye on something, they can do so whenever they wish. We should keep the defaults at something that will not kill the web server by accident when 5-10 people are all looking at it at the same time.
> 
> Argument can be other way round too.

I'll agree 15 mins may be a bit much, but I'm really against going below 5 as the default. Remember we're talking about the thing that every single person will get whenever they come to these dashboards by default. If people really need to see something in finer grained detail or over a longer period of time, or if they want a faster refresh, we're not stopping them from changing things at all. We need to keep a sane value so people don't kill their webservers by default.

**Comment by sharmay** [comment]
> > > 60s is way too frequent a default IMO. We had them at 15s or 30s on our internal dashboards by accident and just 3 or 4 people keeping those dashboards open and refreshing was pegging the CPU and crashing the web server. I went with 15mins across the board in general and would say no lower than maybe 5 mins for the Overview, if we even really feel the need to change this.

We are comparing two different systems, I have heard that Prometheus has good performance compare to graphite.

**Comment by keithf4** [comment]
I've changed the refresh for the overview dashboards to 5 minutes. It takes several minutes for Grafana to calculate a change in state anyway, so doing it any faster causes unnecessary load. I think the 5 min default is a good balance between keeping a faster refresh and allowing for possible unknown performance issues when keeping a faster refresh interval on a TSDB interface.

**Comment by keithf4** [comment]
You're grep's were a little two broad. 

The only "from" field that matters is the one in the "time" section
```
  "time": {
    "from": "now-5m",
    "to": "now"
```

And the only "editable" field that matters for what we're doing here is the one at the top level and those are false. Not sure what all those lower level ones in the ETCD dashboard are. Checking again and nothing in that dashboard is actually editable. Don't see anything in the web interface that's controlling any other editable properties and don't want to edit any json manually unless I know what it's doing. Maybe newer versions of grafana add something? Will see when I update for 6.5 (https://github.com/CrunchyData/pgmonitor/issues/160)

**Pull request merged**
