### PR TITLE
Update dashboard links to use supported endpoints using the dashboard…

### PR DESCRIPTION
**Pull request by dsessler7**
… uids.

[sc-19940]

# Description  

*Please fill this template out fully; failure to do so can result in rejection of your PR.*

Please describe the changes made by your PR. This description should be at a high-level but detailed enough that a reviewer understands the scope of the fix or enhancement and can easily judge the PRs validity at addressing the stated issue/feature. Please fully describe any new or changed feature and whether said change is user-facing or not:

Grafana removed support for the `/dashboard/db/:slug` endpoint in [this PR](https://github.com/grafana/grafana/pull/35104) which first took effect in Grafana v8.0.0. We still have a number of links that use this unsupported URL format which results in these links breaking when using Grafana v8 or higher. This PR changes these URLs to use the supported format which uses a given dashboard's uid.

Please indicate what kind of change your PR includes (multiple selections are acceptable):

- [x] Bugfix
- [ ] Enhancement
- [ ] Breaking Change
- [ ] Documentation

PRs should be against existing issues, so please list each issue using a separate 'closes' line:

closes #

If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.

depends on #

If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.

## Testing
*None of the testing listed below is optional.*

- Installation method:  
    - [ ] Binary install from source, version:  
    - [ ] OS package repository, distro, and version:  
    - [ ] Local package server, version:  
    - [ ] Custom-built package, version:  
    - [x] Other:  
- [ ] PostgreSQL, Specify version(s):  
- [ ] docs tested with hugo version(s):  

### Code testing

Have you tested your changes against:
- [ ] RedHat/CentOS
- [ ] Ubuntu
- [ ] SLES
- [x] Not applicable

If your code touches postgres_exporter, have you:
- [ ] Tested against all versions of PostgreSQL affected
- [ ] Ensure that exporter runs with no scrape errors
- [x] Not applicable

If your code touches node_exporter, have you:
- [ ] Ensure that exporter runs with no scrape errors
- [x] Not applicable

If your code touches Prometheus, have you:
- [ ] Ensured all configuration changes pass `promtool check config`
- [ ] Ensured all alert rule changes pass `promtool check rules`
- [ ] Prometheus runs without issue
- [ ] Alertmanager runs without issue
- [x] Not applicable

If your code touches Grafana, have you:
- [x] Ensured Grafana runs without issue
- [x] Ensured relevant dashboards load without issue
- [ ] Not applicable

### Checklist:
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

### CODE REVIEW

**Review by hunleyd — APPROVED** [review]

**Review by keithf4 — CHANGES_REQUESTED** [review]
Looks great.

Would you mind doing a changelog fragment so this can be easily added to the release notes for the next version? See https://github.com/CrunchyData/pgmonitor/tree/development/changelogs and examples in https://github.com/CrunchyData/pgmonitor/tree/development/changelogs/fragments

**Review by pgguru — DISMISSED** [review]
Any backwards-compatibility concerns, or we're definitely only using Grafana 8+ going forward (or prior versions also include this ID support)?

**Comment by keithf4** [comment]
> Any backwards-compatibility concerns, or we're definitely only using Grafana 8+ going forward (or prior versions also include this ID support)?

Minimum version of Grafana for 4.9 will be 8.5
https://github.com/CrunchyData/pgmonitor/blob/development/changelogs/fragments/283.yml

**Comment by dsessler7** [comment]
It seems y'all name your changelog fragment file according to the Issue number that the change is closing... This PR doesn't fix any specific GH issue (yet). Should I create an Issue? Or should I just name the changelog fragment after the PR number?

Also, in response to @pgguru's question of backwards compatibility - Grafana started supporting the URL format that I've switched these links to in v5. They just removed support for the old URL format in v8. So, even if we did allow for using v7 Grafana, these links would still work.

**Comment by keithf4** [comment]
> It seems y'all name your changelog fragment file according to the Issue number that the change is closing... This PR doesn't fix any specific GH issue (yet). Should I create an Issue? Or should I just name the changelog fragment after the PR number?
> 
You can just use the PR number for now. Thanks!

**Review by pgguru — APPROVED** [review]

**Review by jchancojr — APPROVED** [review]

**Pull request merged**
