### PR TITLE
Reorganize repository files structure

### PR DESCRIPTION
**Pull request by keithf4**
# Description  

Reorganize file structure of repository to make it easier for packaging and also make it easier to clearly see which files are intended for specific platforms.

Also more clearly named the "queries_common.yml" to "queries_global.yml" to indicate it is mainly meant for the global exporter that is running.

Dropped PG 9.5 support

```
$ tree -I hugo
.
├── alertmanager
│   ├── common
│   │   └── crunchy-alertmanager.yml
│   ├── linux
│   │   ├── crunchy-alertmanager-service-rhel.conf
│   │   └── sysconfig.alertmanager
│   └── windows
├── blackbox_exporter
│   ├── common
│   │   ├── blackbox_exporter.sysconfig
│   │   └── crunchy-blackbox.yml
│   ├── linux
│   └── windows
├── crontab.txt
├── grafana
│   ├── common
│   │   ├── Bloat_Details.json
│   │   ├── CRUD_Details.json
│   │   ├── crunchy_grafana_datasource.yml
│   │   ├── ETCD_Details.json
│   │   ├── PGBackrest.json
│   │   ├── PGBouncer.json
│   │   ├── PG_Details.json
│   │   ├── PG_Overview.json
│   │   ├── Prometheus_Alerts.json
│   │   ├── QueryStatistics.json
│   │   └── TableSize_Details.json
│   ├── containers
│   │   ├── crud_details.json
│   │   ├── pgbackrest.json
│   │   ├── pod_details.json
│   │   ├── postgresql_details.json
│   │   ├── postgresql_overview.json
│   │   ├── postgresql_service_health_overview.json
│   │   └── prometheus_alerts.json
│   ├── linux
│   │   ├── crunchy_grafana_dashboards.yml
│   │   ├── Filesystem_Details.json
│   │   ├── OS_Details.json
│   │   ├── OS_Overview.json
│   │   └── Overview.json
│   └── windows
│       ├── crunchy_grafana_dashboards.yml
│       ├── OS_Details.json
│       └── OS_Overview.json
├── LICENSE
├── node_exporter
│   ├── common
│   ├── linux
│   │   ├── ccp_io_queue.sh
│   │   ├── crunchy-node-exporter-service-rhel.conf
│   │   └── sysconfig.node_exporter
│   └── windows
├── pgbadger
│   └── run_pgbadger.py
├── postgres_exporter
│   ├── common
│   │   ├── pg10
│   │   │   ├── queries_general.yml
│   │   │   ├── queries_pg_stat_statements.yml
│   │   │   └── setup.sql
│   │   ├── pg11
│   │   │   ├── queries_general.yml
│   │   │   ├── queries_pg_stat_statements.yml
│   │   │   └── setup.sql
│   │   ├── pg12
│   │   │   ├── queries_general.yml
│   │   │   ├── queries_pg_stat_statements_full.yml
│   │   │   ├── queries_pg_stat_statements.yml
│   │   │   └── setup.sql
│   │   ├── pg13
│   │   │   ├── queries_general.yml
│   │   │   ├── queries_pg_stat_statements_full.yml
│   │   │   ├── queries_pg_stat_statements.yml
│   │   │   └── setup.sql
│   │   ├── pg96
│   │   │   ├── queries_general.yml
│   │   │   └── setup.sql
│   │   ├── queries_bloat.yml
│   │   ├── queries_global.yml
│   │   ├── queries_nodemx.yml
│   │   ├── queries_per_db.yml
│   │   └── queries_pgbouncer.yml
│   ├── linux
│   │   ├── crunchy-postgres-exporter@.service
│   │   ├── pg10
│   │   │   ├── sysconfig.postgres_exporter_pg10
│   │   │   └── sysconfig.postgres_exporter_pg10_per_db
│   │   ├── pg11
│   │   │   ├── sysconfig.postgres_exporter_pg11
│   │   │   └── sysconfig.postgres_exporter_pg11_per_db
│   │   ├── pg12
│   │   │   ├── sysconfig.postgres_exporter_pg12
│   │   │   └── sysconfig.postgres_exporter_pg12_per_db
│   │   ├── pg13
│   │   │   ├── sysconfig.postgres_exporter_pg13
│   │   │   └── sysconfig.postgres_exporter_pg13_per_db
│   │   ├── pg96
│   │   │   ├── sysconfig.postgres_exporter_pg96
│   │   │   └── sysconfig.postgres_exporter_pg96_per_db
│   │   ├── pgbackrest-info.sh
│   │   ├── pgmonitor.conf
│   │   └── queries_backrest.yml
│   └── windows
│       ├── queries_common.yml
│       └── queries_per_db.yml
├── prometheus
│   ├── common
│   │   ├── alert-rules.d
│   │   │   ├── crunchy-alert-rules-blackbox.yml.example
│   │   │   ├── crunchy-alert-rules-etcd.yml.example
│   │   │   └── crunchy-alert-rules-pg.yml.example
│   │   └── auto.d
│   │       ├── ProductionDB.yml.example
│   │       └── ReplicaDB.yml.example
│   ├── containers
│   │   ├── alert-rules.d
│   │   │   └── crunchy-alert-rules-pg.yml.containers.example
│   │   ├── auto.d
│   │   └── crunchy-prometheus.yml.containers
│   ├── linux
│   │   ├── alert-rules.d
│   │   │   └── crunchy-alert-rules-node.yml.example
│   │   ├── auto.d
│   │   │   ├── ProductionOS.yml.example
│   │   │   └── ReplicaOS.yml.example
│   │   ├── crunchy-prometheus-service-rhel.conf
│   │   ├── crunchy-prometheus.yml
│   │   └── sysconfig.prometheus
│   └── windows
│       ├── alert-rules.d
│       │   └── crunchy-alert-rules-wmi.yml.example
│       ├── auto.d
│       └── crunchy-prometheus.yml
└── README.md

45 directories, 90 files
```

Fixes (issue) #189

## Type of change  
Please check all options that are relevant  
- [ ] Bug fix (change which fixes an issue)  
- [ ] Feature (change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)  
- [ ] Documentation update only  

# How Has This Been Tested?  

**Tested Configuration**:  
- [ ] CentOS, Specify version(s):  
- [ ] PostgreQL, Specify version(s):  
- [ ] docs tested with hugo <0.60  

Tested with playbook(s):  
# Checklist:  
- I have made corresponding changes to:  
    - [ ] the documentation  
    - [ ] the release notes  
    - [ ] the upgrade doc

### CODE REVIEW

**Comment by hunleyd** [comment]
this is *really* hard to visualize on github. can you maybe do a `tree` style output for before and after as a comment here so we can see what it looks like post-re-org @keithf4 ?

**Comment by keithf4** [comment]
> this is _really_ hard to visualize on github. can you maybe do a `tree` style output for before and after as a comment here so we can see what it looks like post-re-org @keithf4 ?

Added tree to PR description

**Review by hunleyd — APPROVED** [review]

**Comment by sharmay** [comment]
Couple requests
1. Move exporters one level up and remove `exporters` top level folder
2. postgres/<pg major>/
3. Remove version from query files and move them in versioned folder
4. Split prometheus in two folders prometheus and alertmanager
5. .win extension not required `crunchy-prometheus.yml.win`

**Comment by keithf4** [comment]
> Couple requests
> 

> 3. Remove version from query files and move them in versioned folder

We discussed this before extensively on a hangout and determined that the version was still needed for clarity on what the contents of that folder actually are.

**Comment by sharmay** [comment]
> > Couple requests
> 
> > 1. Remove version from query files and move them in versioned folder
> 
> We discussed this before extensively on a hangout and determined that the version was still needed for clarity on what the contents of that file actually are.

But I am suggesting PG version at one level up, this will get us consistent file names.

**Review by pgguru — APPROVED** [review]

**Comment by keithf4** [comment]
> Couple requests
> 
> 1. Move exporters one level up and remove `exporters` top level folder

Done

> 2. postgres//

Not sure what this is referring to

> 3. Remove version from query files and move them in versioned folder

Done. Renamed `queries_pg##.yml` to `queries_general.yml`

> 4. Split prometheus in two folders prometheus and alertmanager

Done

> 5. .win extension not required `crunchy-prometheus.yml.win`

Done

**Review by hunleyd — DISMISSED** [review]

**Review by pgguru — APPROVED** [review]

**Review by sharmay — APPROVED** [review]

**Review by sharmay — APPROVED** [review]

**Review by pgguru — APPROVED** [review]

**Pull request merged**
